### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by tomspeak** [tomspeak/quiet-hacker-news#2]

**Comment by James-E-Adams** [comment]
Come up with a logo yet? Maybe the YCombinator Y with a "shh" or a "zz", copyright issues permitting?

**Comment by tomspeak** [comment]
Unfortunately not, the only thing worse than my Go skills are my design skills!

Everyday the lack of icon chips at me, I’ll hopefully have a creative fit of rage soon.

**Comment by James-E-Adams** [comment]
Yeah - `design skills` are on the list to one day invest some time into!

**Comment by tomspeak** [comment]
If you get some before me, feel free to send a favicon my way

**Comment by James-E-Adams** [comment]
Ez. Off-topic, but having never looked at golang code before, I'm impressed
how little code is required to make this.

**Comment by tomspeak** [comment]
I cannot recommend the language enough, I have been tinkering with it for the past few weeks and it has been a breath of fresh air coming from Node. E-mail me at hello@tomspeak.co.uk if you ever decide to, got some nice learning resources piled up.

**Comment by James-E-Adams** [comment]
Done. :)

**Comment by feiss** [comment]
still without favicon?
![favicon1](https://user-images.githubusercontent.com/359872/61638418-a6cdf500-ac99-11e9-988e-a83a7e4b3fae.png)
![favicon0](https://user-images.githubusercontent.com/359872/61638419-a7668b80-ac99-11e9-9cb8-19d96a081b96.png)
![favicon2](https://user-images.githubusercontent.com/359872/61638420-a7668b80-ac99-11e9-8c7b-19220fd45667.png)

feel free to choose and use

**Comment by wgx** [comment]
How about this? (Run it through http://www.favicomatic.com/ to get the multi-size assets)

![quiethn](https://user-images.githubusercontent.com/930099/61694918-61a5d380-ad2a-11e9-8922-7842acc3f35c.png)

**Comment by tomspeak** [comment]
Thank you so much for the contribution @feiss and @wgx 💓
