### ISSUE TITLE
Strip out 'Ask HN', 'Jobs HN' etc

### ISSUE THREAD

**Issue by tomspeak** [tomspeak/quiet-hacker-news#5]

**Comment by benhowdle89** [comment]
A head start: 

```

**Comment by benhowdle89** [comment]
Actually, just check for the `Text` key in the JSON response. If it's there, it's not a link, so bin it.

**Comment by richarddewit** [comment]
One slipped through:

30. Show HN: Metaballs
(varun.ca)
