### ISSUE TITLE
Enforce https

### ISSUE THREAD

**Issue by tomspeak** [tomspeak/quiet-hacker-news#7]
Currently you can land on `http://` and continue on your merry way, we want to force `https://` upon people.

**Comment by preeteshjain** [comment]
I don't know what web server and OS you are using for the server, but you can try (Certbot)[https://certbot.eff.org]. It takes only a few minutes to set it up. Plus it's free.

**Comment by tomspeak** [comment]
Currently using LetsEncrypt with Heroku hobby dyno.

Looking into the easiest way to set this up, cert-bot looks great. May move over to a simple DO droplet.
